---
abstract: 'Run external commands'
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-Proc
requires:
  AnyEvent: '0'
  AnyEvent::Handle: '0'
  AnyEvent::Util: '0'
  Coro::Channel: '0'
  Exporter: '0'
  POSIX: '0'
  Scalar::Util: '0'
  Try::Tiny: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/zurborg/libanyevent-proc-perl/issues
  homepage: https://github.com/zurborg/libanyevent-proc-perl
  repository: https://github.com/zurborg/libanyevent-proc-perl.git
version: '0.101'
x_contributors:
  - 'David Zurborg <zuborg@cpan.org>'
